### ISSUE TITLE
[QUESTION] - Is it possible to check the CircleCI checks?

### ISSUE THREAD

**Issue by amioranza** [fountainhead/action-wait-for-check#11]
Hi,

I'm trying to check the CircleCi events, is it possible to check for this kind of event using this gh action?

Thanks.

**Comment by wms** [comment]
I don't see why this _shouldn't_ be possible - although this Action (obviously) needs to run via GH Actions, it's only observing the status of _checks_, so it shouldn't matter where/how that check is being executed.

**Comment by amioranza** [comment]
So, I'm trying to capture this check with no success:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/30518346/108368806-a0875e00-71d9-11eb-82df-75d32ad93c42.png">

What name I should use at the checkName field?

I tried the full name, just run, name with status and all have the same behavior, the gh action never matches the check.

Thanks.

**Comment by wms** [comment]
Have you enabled the CircleCI integration with the GH Checks API? https://circleci.com/blog/see-the-status-of-your-circleci-workflows-in-github/

**Comment by amioranza** [comment]
Awesome! Now it is working! Thank you!!!
<img width="529" alt="image" src="https://user-images.githubusercontent.com/30518346/108376195-7df94300-71e1-11eb-9b60-2ac2a66b4ebb.png">

**Comment by jurgen-weber-deltatre** [comment]
@amioranza  what did you use in the checkName field? I am having the same sort of problem but i do not think it is permissions.

**Comment by amioranza** [comment]
@jurgen-weber-deltatre you have to change your repo enabling the option o the doc linked and then you can use the step name to check.

**Comment by amioranza** [comment]
Sorry, I don't know how can I help you. I don't remember where I used this action anymore and the options used.
