### ISSUE TITLE
Waiting for check times out

### ISSUE THREAD

**Issue by sean-hill** [fountainhead/action-wait-for-check#8]
Hi there! Awesome package by the way. I just can't seem to get it to work :) I'm waiting for this check to pass on a PR:

![image](https://user-images.githubusercontent.com/1205866/97998946-f578a300-1da7-11eb-8265-b44b012a9c30.png)
As you can see, it has completed.

And have setup this action as follows:

![image](https://user-images.githubusercontent.com/1205866/97999027-0de8bd80-1da8-11eb-8534-a0f08d9e806e.png)
But it just sits there and polls forever.

I have tried the `github.pull_request.head.sha` option for the `ref` as well with no luck. Any ideas?

Thank you!

**Comment by frixatrix** [comment]
@sean-hill Try to check logs, I had similar issue and resolved by `ref: ${{ github.head_ref }}` for pull requests.
Issue was in wrong sha.
